=== MarianoRoldan47/EjerciciosLMSGI/DTD/examen intento/examen.dtd
<!ELEMENT fruteria (#PCDATA | frutas | verduras | ofertas | contacto)*>

<!ELEMENT frutas ANY>
<!ELEMENT verduras (tomate+, brocoli, coliflor)>
<!ELEMENT ofertas (oferta)+>
<!ELEMENT oferta (#PCDATA | precio)*>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT contacto EMPTY>
<!ELEMENT manzana EMPTY>
<!ELEMENT pera EMPTY>
<!ELEMENT melon EMPTY>
<!ELEMENT tomate (delTerreno)?>
<!ELEMENT delTerreno (#PCDATA)>
<!ELEMENT brocoli (#PCDATA)>
<!ELEMENT coliflor (#PCDATA)>

<!ENTITY % atributoColor "color (amarillo | verde | rojo | marron | blanco ) 'verde' ">
<!ENTITY % atributoID "id ID #REQUIRED">

<!ATTLIST oferta articulo IDREF #REQUIRED>
<!ATTLIST contacto telefono CDATA #FIXED "642160405">
<!ATTLIST manzana %atributoColor;
                  %atributoID;>
<!ATTLIST pera %atributoColor;
               %atributoID;>
<!ATTLIST melon %atributoColor;
                %atributoID;>

<!ATTLIST tomate %atributoID;>
<!ATTLIST brocoli %atributoID;>
<!ATTLIST coliflor %atributoID;>

<!ENTITY nombreFruteria "Fruteria Manolo S.L.">

=== MarianoRoldan47/EjerciciosLMSGI/DTD/examen intento/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fruteria SYSTEM "examen.dtd">
<fruteria> &nombreFruteria; 
	<frutas>
		<manzana id="mzn" color="amarillo" />
		<pera id="per" color="verde" />
		<melon id="mln" color="verde" />
	</frutas>
	<verduras>
		<tomate id="tmt">
			<delTerreno>De Rute</delTerreno>
		</tomate>
		<brocoli id="brc">

		</brocoli>
		<coliflor id="clf">

		</coliflor>
	</verduras>
	<ofertas>
		<oferta  articulo="mzn">
			2x1 
			<precio>10€</precio>
		</oferta>
	</ofertas>
	<contacto telefono="642160405" />
</fruteria>
