=== MarianoRoldan47/EjerciciosLMSGI/XSD/crepusculo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="crepusculo" type="tipoCrepusculo"/>
  
  <xs:complexType name="tipoCrepusculo">
    <xs:sequence>
      <xs:element name="entrega" maxOccurs="unbounded" type="tipoEntrega" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="tipoEntrega" mixed="true">
    <xs:sequence>
      <xs:element name="actor" maxOccurs="unbounded" type="tipoActor"/>
    </xs:sequence>
    <xs:attribute name="numero" type="tipoNumeroEntrega" />
  </xs:complexType>

  <xs:simpleType name="tipoNumeroEntrega">
    <xs:restriction base="xs:string">
      <xs:pattern value="[1-5]"></xs:pattern>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="tipoActor">
    <xs:choice>
      <xs:element name="humano" minOccurs="0" />
      <xs:element name="vampiro" minOccurs="0"/>
    </xs:choice>
    <xs:attribute name="nombre" />
    <xs:attribute name="representaA" type="tipoRepresentaA">
     
    </xs:attribute>

  </xs:complexType>
  <xs:simpleType name="tipoRepresentaA">
        <xs:restriction base="xs:string">
          <xs:enumeration value="Bella" />
          <xs:enumeration value="Edward" />
          <xs:enumeration value="Carlisle" />
        </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== MarianoRoldan47/EjerciciosLMSGI/XSD/crepusculo.xml
<?xml version="1.0" encoding="UTF-8"?>
<crepusculo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="crepusculo.xsd">

    <entrega numero="1">Crepusculo <actor nombre="Kristen Stewart" representaA="Bella"></actor>
        <actor
            nombre="Robert Pattinson" representaA="Edward"></actor>
        <actor nombre="Peter Facinelli"
            representaA="Carlisle"></actor>
    </entrega>
    <entrega numero="2">Luna Nueva <actor nombre="Kristen Stewart" representaA="Bella"></actor>
        <actor
            nombre="Robert Pattinson" representaA="Edward"></actor>
        <actor nombre="Peter Facinelli"
            representaA="Carlisle"></actor>
    </entrega>
    <entrega numero="3">Eclipse <actor nombre="Kristen Stewart" representaA="Bella">
            <humano />
        </actor>
        <actor nombre="Robert Pattinson" representaA="Edward">
            <vampiro />
        </actor>
        <actor nombre="Peter Facinelli" representaA="Carlisle"></actor>
    </entrega>
    <entrega numero="4">Amanecer (primera parte) <actor nombre="Kristen Stewart"
            representaA="Bella">
            <humano />
        </actor>
        <actor nombre="Robert Pattinson" representaA="Edward">
            <vampiro />
        </actor>
        <actor nombre="Peter Facinelli" representaA="Carlisle"></actor>
    </entrega>
    <entrega numero="5">Amanecer (segunda parte) <actor nombre="Kristen Stewart" representaA="Bella">
            <humano />
        </actor>
        <actor nombre="Robert Pattinson" representaA="Edward">
            <vampiro />
        </actor>
        <actor nombre="Peter Facinelli" representaA="Carlisle"></actor>
    </entrega>

</crepusculo>
