=== MarianoRoldan47/EjerciciosLMSGI/DTD/Examen_DTD/examen.dtd
<!ELEMENT proyectosConstruccion (#PCDATA | proyecto)*>
<!ELEMENT personal (perito?,constructor+, conductoresMaquinaria+)>
<!ELEMENT perito EMPTY>
<!ELEMENT constructor EMPTY>
<!ELEMENT conductoresMaquinaria EMPTY>
<!ELEMENT proyecto (personal , maquinaria , (pagador | pagadoPorLaEmpresa))>
<!ELEMENT maquinaria (maquina+)>
<!ELEMENT maquina EMPTY>

<!ELEMENT pagador (#PCDATA)>
<!ELEMENT pagadoPorLaEmpresa EMPTY>

<!ENTITY % nombrePersonal "nombre CDATA #IMPLIED">
<!ATTLIST perito %nombrePersonal;
                 id ID #REQUIRED>
<!ATTLIST constructor %nombrePersonal;
                      id ID #REQUIRED>
<!ATTLIST conductoresMaquinaria %nombrePersonal;
                                id ID #REQUIRED>

<!ATTLIST proyecto nombre CDATA #REQUIRED>

<!ATTLIST maquina usadaPor IDREFS #IMPLIED>
<!ATTLIST maquina conductor IDREF #IMPLIED>
<!ATTLIST proyectosConstruccion telefonoConstructora CDATA #FIXED "555666777">
<!ATTLIST maquina nombre (Excavadora | Camion | Taladro | Alisadora) "Taladro">


<!ENTITY nombreConstructora "Constructora Hermanos Roldan S.L.">

=== MarianoRoldan47/EjerciciosLMSGI/DTD/Examen_DTD/examen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE proyectosConstruccion SYSTEM "examen.dtd">
<proyectosConstruccion telefonoConstructora="555666777"> &nombreConstructora;
	<proyecto nombre="Construccion edificio ayuntamiento">
		<personal>
			<perito nombre="Alejandro Cabello Lara" id="acl" />
			<constructor nombre="Rafael Garcia Muñoz" id="rgm" />
			<constructor nombre="Alberto Jimenez García" id="ajg" />
			<conductoresMaquinaria nombre="Jose Alberto Ramirez Sarmiento" id="jars" />
		</personal>
		<maquinaria>
			<maquina nombre="Excavadora" conductor="jars" />
			<maquina nombre="Camion" conductor="jars" />
			<maquina nombre="Taladro" usadaPor="rgm ajg" />
			<maquina nombre="Alisadora" usadaPor="rgm ajg" />
		</maquinaria>
		<pagador>Ayuntamiento</pagador>
	</proyecto>
	<proyecto nombre="Arreglo en la sede de la constructora">
		<personal> 
			<constructor nombre="Rafael Roldan Muñoz" id="rrm" />
			<constructor nombre="Alberto Jimenez Arcos" id="aja" />
			<conductoresMaquinaria nombre="Jose Ramirez Sarmiento" id="jrs" />
		</personal>
		<maquinaria>
			<maquina nombre="Excavadora" conductor="jrs" />
			<maquina nombre="Camion" conductor="jrs" />
			<maquina nombre="Taladro" usadaPor="rrm aja" />
			<maquina nombre="Alisadora" usadaPor="rrm aja" />
		</maquinaria>
		<pagadoPorLaEmpresa />
	</proyecto>
	
</proyectosConstruccion>
