=== MarianoRoldan47/EjerciciosLMSGI/XSD/Apuntes/15-elemento-con-descendientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="superheroe">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="amigo" type="amigosSuperheroe" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  
  <xs:complexType name="amigosSuperheroe">
    <xs:sequence>
      <xs:element name="amigoDeSuperheroe" type="textoNoVacio"/>
    </xs:sequence>
  </xs:complexType>  
  
  <xs:simpleType name="textoNoVacio">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== MarianoRoldan47/EjerciciosLMSGI/XSD/Apuntes/15-elemento-con-descendientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<superheroe xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="15-elemento-con-descendientes.xsd">
  <nombre>Hulk</nombre>
  <amigo>
    <amigoDeSuperheroe>Thor</amigoDeSuperheroe>
  </amigo>
  <amigo>
    <amigoDeSuperheroe>Hulk</amigoDeSuperheroe>
  </amigo>
  <amigo>
    <amigoDeSuperheroe>Bulleye</amigoDeSuperheroe>
  </amigo>
</superheroe>
